# .github/workflows/app.yaml
name: Docker
on:
    push:
        paths:
        - Dockerfile

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker image
        run: |
          docker build -t ngspetsc:latest .
      - name: Push Docker image
        run: |
          docker tag ngspetsc:latest urzerbinati/ngspetsc:latest
          docker push urzerbinati/ngspetsc:latest
