# .github/workflows/app.yaml
name: ngsPETSc FEniCSx tests
on: 
    push:
      branches-ignore:    
      - 'no-ci/*'

    schedule:
    - cron:  '30 10 7,14,21,28 * *'

jobs:
  ngsolve_tests:
    runs-on: ubuntu-latest
    container: dolfinx/dolfinx:latest
    timeout-minutes: 20

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install Netgen and ngsPETSc
        run: |
          pip3 install netgen-mesher \
          && pip3 install pylint \
          && export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python3.10/site-packages \
          && NGSPETSC_NO_INSTALL_REQUIRED=ON pip install .

      - name: Check formatting
        run: |
          make lint
          make lint_test

      - name: Run test suite in serial
        run: |
          pytest -v tests/test_fenicsx.py
