# .github/workflows/app.yaml
name: ngsPETSc
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container: urzerbinati/ngspetsc:latest
    timeout-minutes: 20

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install ngsPETSc
        run: |
          python -m pip install .

      - name: Check formatting
        run: |
          make lint

      - name: Run test suite in serial
        run: |
          pytest -v tests/

      - name: Run test suite in parallel
        run: |
          mpirun --allow-run-as-root -n 2 pytest -v --with-mpi tests/
