# .github/workflows/app.yaml
name: ngsPETSc
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container: urzerbinati/ngspetsc:latest
    timeout-minutes: 20

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install ngsPETSc
        run: |
          python -m pip install .

      - name: Check formatting
        run: |
          pylint --disable=C0103,C0321,E1101,R0914,R0903,R0205 --variable-naming-style=camelCase --class-naming-style=PascalCase --argument-naming-style=camelCase --attr-naming-style=camelCase ngsPETSc
          pylint --disable=C0103,C0321,E1101,R0914,R0903,R0205 --variable-naming-style=camelCase --class-naming-style=PascalCase --argument-naming-style=camelCase --attr-naming-style=camelCase tests

      - name: Run test suite
        run: |
          pytest tests/
