name: Publish release

# To make a release the following steps should be done:
# 1. Bump the version number in the 'pyproject.toml'
# 2. Manually trigger this workflow, passing in the new version number

on:
  workflow_dispatch:
    inputs:
      version:
      description: The version number to release, this should include the 'v' prefix
      type: string
      required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build source and wheel distributions
        run: |
          pip install poetry
          poetry build

      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  pypi_publish:
    name: Upload release to PyPI
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: release
    permissions:
      id-token: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  github_release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Create GitHub release and upload dist files
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create --title ${{ inputs.version }} --generate-notes ${{ inputs.version }} dist/*
